// Generated by CoffeeScript 1.8.0
(function() {
  setAppName('ExampleApp');

  window.menuBarIcon = {};

  window.groupTypes = [
    {
      name: 'reporter',
      text: 'Simple Event Reporter',
      image: './images/red-bracket-icon.png',
      tagContents: function(group) {
        var _ref;
        return "" + ((_ref = group.contentAsText()) != null ? _ref.length : void 0) + " characters";
      },
      contentsChanged: function(group, firstTime) {
        return console.log('This group just changed:', group.contentAsText());
      },
      deleted: function(group) {
        return console.log('You deleted this group:', group);
      }
    }
  ];

}).call(this);

//# sourceMappingURL=simple-example.solo.js.map
