// Generated by CoffeeScript 1.8.0
(function() {
  var buildFunction,
    __hasProp = {}.hasOwnProperty;

  buildFunction = function(funcStr) {
    var argList, body;
    argList = funcStr.substring(funcStr.indexOf('(') + 1, funcStr.indexOf(')'));
    body = funcStr.substring(funcStr.indexOf('{') + 1, funcStr.lastIndexOf('}'));
    return new Function(argList, body);
  };

  self.window = self;

  self.addEventListener('message', function(event) {
    var func, name, _ref;
    if (event.data.hasOwnProperty('setFunction')) {
      self.action = buildFunction(event.data.setFunction);
    }
    if (event.data.hasOwnProperty('runOn')) {
      self.postMessage(typeof self.action === "function" ? self.action.apply(self, event.data.runOn) : void 0);
    }
    if (event.data.hasOwnProperty('install')) {
      _ref = event.data.install;
      for (name in _ref) {
        if (!__hasProp.call(_ref, name)) continue;
        func = _ref[name];
        self[name] = buildFunction(func);
      }
    }
    if (event.data.hasOwnProperty('import')) {
      return importScripts.apply(null, event.data["import"]);
    }
  }, false);

}).call(this);

//# sourceMappingURL=worker-solo.js.map
