// Generated by CoffeeScript 1.8.0
(function() {
  self.addEventListener('message', function(event) {
    var argList, body, funcStr;
    if (event.data.hasOwnProperty('setFunction')) {
      funcStr = event.data.setFunction;
      argList = funcStr.substring(funcStr.indexOf('(') + 1, funcStr.indexOf(')'));
      body = funcStr.substring(funcStr.indexOf('{') + 1, funcStr.lastIndexOf('}'));
      self.action = new Function(argList, body);
    }
    if (event.data.hasOwnProperty('runOn')) {
      return self.postMessage(typeof self.action === "function" ? self.action.apply(self, event.data.runOn) : void 0);
    }
  }, false);

}).call(this);

//# sourceMappingURL=worker.solo.js.map
