// Generated by CoffeeScript 1.7.1
(function() {
  window.testAppSetup = function() {
    return window.LE = new LurchEditor(document.getElementById('editor'));
  };

}).call(this);

//# sourceMappingURL=testapp.map
